meta_product_name: "Booklub"
meta_title: "Booklub - Connect with book lovers around the world"
meta_description: "Relevant description"
meta_image: "booklubog.png" # should exist in `app/assets/images/`
