meta_product_name: "Booklub"
meta_title: "Booklub - Connect with book lovers around the world"
meta_description: "Booklub is the best place to join or create book clubs to discuss and exchange ideas with friends and people around the globe."
meta_image: "booklubog.png" # should exist in `app/assets/images/`
